### ISSUE TITLE
Shader rendering error

### ISSUE THREAD

**Issue by kolegovlawyer** [blackears/terrain_layered_shader#1]
![изображение](https://github.com/blackears/terrain_layered_shader/assets/93939095/2714f310-70fa-48e2-80c9-c60f460a50dc)

@blackears 
Hello, i stuck in some troubles into shader rendering on Vulkan(OpenGL) Ubuntu. My friend with same stack have same troubles. In Godot editor all looks cool, but when scene is run, in window shader doesnt work. 
I use latest default version of https://github.com/blackears/terrain_layered_shader

`E 0:00:01:0181   Tokenizer: Unknown character #35: '#'
  <C++ Source>   :29

E 0:00:01:0181   set_code: Shader compilation failed.
  <C++ Error>    Condition "err != OK" is true.
  <C++ Source>   servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp:145 @ set_code()

E 0:00:01:0743   version_get_shader: Parameter "version" is null.
  <C++ Source>   ./servers/rendering/renderer_rd/shader_rd.h:165 @ version_get_shader()
`

**Comment by blackears** [comment]
Not sure.  My guess is its a bug in Godot itself.  Do you know which file the ` Tokenizer: Unknown character #35: '#'` is referring to?  Ie, a GDScript file vs one of the shader files?

If you can send me a file that demonstrates this, I can have a look at it.  Might need to submit it to the Godot team too if it looks like an engine issue.

**Comment by kolegovlawyer** [comment]
> Not sure. My guess is its a bug in Godot itself. Do you know which file the ` Tokenizer: Unknown character #35: '#'` is referring to? Ie, a GDScript file vs one of the shader files?
> 
> If you can send me a file that demonstrates this, I can have a look at it. Might need to submit it to the Godot team too if it looks like an engine issue.

The solution has been found. In Ubuntu and presumably other Linux systems, you need to specify the absolute path in the shader code to the tool:

`#include "res://addons/terrain_layered_shader/shaders/terrain_tools.gdshaderinc"`

**Comment by blackears** [comment]
Looks like Godot changed the way it handled shaders. I've updated the code to use the new #include convention.  I also changed the defaults of a few parameters, but you don't need to upgrade if your shader code is working properly.
